[package]
name = "hotfnl"
description = "A lightweight Rust library for dynamic library patching and hot-reloading on Linux"
version.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true
edition.workspace = true

[workspace.package]
version = "0.1.1"
repository = "https://github.com/xtilam/hotfnl"
license = "MIT"
authors = ["ztilam60@gmail.com"]
edition = "2024"

[workspace]
members = ["packages/hotfnl-proc-macro", "example/ratatui-app"]

[workspace.dependencies]
crossterm = { version = "0.29.0" }
libloading = { version = "0.9.0" }
notify = { version = "8.2.0" }
toml = { version = "1.1.4" }
anyhow = { version = "1.0.104" }
serde = { version = "1.0.229", features = ["derive"] }
paste = { version = "1.0.15" }
crossbeam-channel = { version = "0.5.16" }
hotfnl = { version = "0.1.0", path = "." }
inventory = "0.3.24"


[dependencies]
libloading = { workspace = true, optional = true }
notify = { workspace = true, optional = true }
toml = { workspace = true, optional = true }
serde = { workspace = true, optional = true, features = ["derive"] }
hotfnl-proc-macro = { version = "0.1.0", path = "packages/hotfnl-proc-macro", optional = true }
paste = { workspace = true, optional = true }
crossbeam-channel = { workspace = true, optional = true }
anyhow = { workspace = true }
inventory = { workspace = true, optional = true }

[features]
default = [
  "dep:libloading",
  "dep:notify",
  "dep:toml",
  "dep:serde",
  "dep:crossbeam-channel",
  "hotfnl-proc-macro/default",
  "dep:paste",
  "dep:inventory",
]

prod = ["hotfnl-proc-macro/prod"]
