[package]
name = "ratatui-app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
crossbeam-channel.workspace = true
crossterm.workspace = true
hotfnl = { version = "0.1.0", path = "../../" }
ratatui = "0.30.2"

[features]
default = ["hotfnl/default"]
prod = ["hotfnl/prod"]

[[bin]]
name = "ratatui"
path = "./main.rs"
