[package]
name = "hotfnl-proc-macro"
version = "0.1.0"
edition = "2024"
authors = ["ztilam60@gmail.com"]
description = "Proc macro for hotfnl"
license = "MIT"
repository = "https://github.com/xtilam/hotfnl"


[lib]
proc-macro = true
path = "lib.rs"

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "fold"] }

[features]
default = []
prod = []
lib = []
