[package]
name = "ratatui-app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow.workspace = true
crossbeam-channel.workspace = true
crossterm.workspace = true
hotfnl.workspace = true
inventory = { workspace = true, optional = true }
ratatui.workspace = true

[features]
default = ["hotfnl/default", "dep:inventory"]
prod = ["hotfnl/prod"]

[[bin]]
name = "ratatui"
path = "./rapp.rs"
